title: 'hellaella.github.io'
description: "A personal blog about some things."
baseurl:
url: "https://hellaella.github.io"

header_pages:
  - index.md
  - contact.md

style: dark

footer: 'follow me on <a href="https://www.instagram.com/benavidxs/">instagram</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
